Style/FrozenStringLiteralComment:
  Enabled: false
Style/StringLiterals:
  ConsistentQuotesInMultiline: true
Style/StringLiteralsInInterpolation:
  EnforcedStyle: single_quotes
Style/AndOr:
  EnforcedStyle: conditionals
Style/AutoResourceCleanup:
  Description: 'Suggests the usage of an auto resource cleanup version of a method (if available).'
  Enabled: true
Style/DoubleNegation:
  Description: 'Checks for uses of double negation (!!).'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#no-bang-bang'
  Enabled: false
Style/AsciiComments:
  Description: 'Use only ascii symbols in comments.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#english-comments'
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false
Style/SingleLineMethods:
  Description: 'Avoid single-line methods.'
  StyleGuide: '#no-single-line-methods'
  Enabled: true

Metrics/ClassLength:
  CountComments: false
  Max: 500
Metrics/ModuleLength:
  CountComments: false
  Max: 500
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 50
NumericLiterals:
  Enabled: false
Metrics/LineLength:
  Max: 120
  IgnoredPatterns: ['\A#']
Metrics/AbcSize:
  Max: 40
Metrics/CyclomaticComplexity:
  Max: 11

Lint/EndAlignment:
  AutoCorrect: true
Lint/DefEndAlignment:
  AutoCorrect: true
Lint/Debugger: # Easy deletion of all debugger breakpoints. false for debug
  Enabled: true

Rails:
  Enabled: true

Documentation:
  Enabled: false

Bundler/OrderedGems:
  TreatCommentsAsGroupSeparators: true

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/initializers/secret_token.rb'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/BlockLength:
  Enabled: false