AllCops:
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'db/schema.rb'
    - 'db/migrate/**/*'
    - 'config/initializers/secret_token.rb'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.5.3
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false